[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-args=-nostartfiles"]


# 由于cargo目前还不能支持读取feature,参见[该issue](https://github.com/rust-lang/cargo/issues/8170)
#[target.'cfg(target_os = "macos")']
#rustflags = ["-C", "link-args=-e __start -nostartfiles"]
#
#[target.'cfg(all(target_os = "macos", feature = "asm"))']
#rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]
